// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW38ZiAGa5hUUcQ4NqBfDebniS2_aqCjU',
    appId: '1:35348409332:android:68d698d2fd25d46ed767a1',
    messagingSenderId: '35348409332',
    projectId: 'tictact-a37a5',
    databaseURL: 'https://tictact-a37a5-default-rtdb.firebaseio.com',
    storageBucket: 'tictact-a37a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAWZEYSsG_7VZOlN7D4yCiST6VvJuSyk',
    appId: '1:35348409332:ios:2d72bb9c45c2e97dd767a1',
    messagingSenderId: '35348409332',
    projectId: 'tictact-a37a5',
    databaseURL: 'https://tictact-a37a5-default-rtdb.firebaseio.com',
    storageBucket: 'tictact-a37a5.appspot.com',
    androidClientId: '35348409332-4itshv0v5llr5d1o7olhaj4eamgse03l.apps.googleusercontent.com',
    iosClientId: '35348409332-g1ipd95slna60c6ne9cfq49qugq1ub7d.apps.googleusercontent.com',
    iosBundleId: 'com.tictac.wrteam.TicTacToe',
  );
}
